// Language context with EST/ENG support
import { createContext, useContext, useState, type ReactNode } from "react";


type Lang = "et" | "en";

const translations = {
  et: {
    nav_home: "Avaleht",
    nav_about: "Meist",
    nav_services: "Teenused",
    nav_faq: "KKK",
    nav_cta: "Kontakt",
    hero_headline: "Taasta tasakaal. Paranda tervist. Tunne end paremini.",
    hero_subtitle: "Élan Kliinik on tõenduspõhine pikaealisuse ja meditsiinilise kaalulangetuse kliinik.",
    hero_cta: "Broneeri konsultatsioon",
    why_title: "Miks valida Élan Kliinik?",
    val_personal_title: "Isiklik kogemus",
    val_personal_desc: "Me teame, mis tunne see on, sest oleme ise selle tee läbi käinud.",
    val_evidence_title: "Tõenduspõhine",
    val_evidence_desc: "Euroopa ravijuhistel baseeruvad ravimid ja protokollid.",
    val_longterm_title: "Pikaajaline tugi",
    val_longterm_desc: "Kuni 24-kuuline terviklik programm.",
    about_title: "Filosoofia",
    about_desc: "Élan Kliinik ühendab kogemused, meditsiini ja personaalse hoolitsuse. Meie eesmärk ei ole vaid kaalunumber, vaid teie Elu kvaliteet.",
    about_cta: "Loe meie lugu",
    footer_nav: "Navigatsioon",
    footer_contact: "Kontakt",
    footer_address: "Aadress",
    footer_phone: "Telefon",
    footer_email: "E-post",
    footer_hours: "Avatud",
    footer_hours_value: "E-R 09:00 – 17:00",
    footer_rights: "Kõik õigused kaitstud.",
    footer_privacy: "Privaatsuspoliitika",
    svc_title: "Teenused",
    po_title: "Élan Private Office",
    po_subtitle: "Isiklik tervisepartnerlus. Piiratud kohtade arv.",
    po_desc: "Mõeldud neile, kes ei tee oma tervises kompromisse. See on täielik meditsiiniline logistika ja proaktiivne tervisejuhtimine inimesele, kes väärtustab aega, privaatsust ja otsest ligipääsu oma arstile.",
    po_price: "Alates 1000 € / kuu",
    po_cta: "Kandideeri liikmeks",
    po_who: "Kellele see on mõeldud?",
    po_page_desc: "Eksklusiivne tervisejuhtimine Dr. Ingmar Lindströmi isikliku järelevalve all.",
    nav_private: "Private Office",
    svc_subtitle: "Tõenduspõhised raviprogrammid, mis on kohandatud teie vajadustele.",
    svc_book: "Broneeri",
    svc1_title: "Meditsiiniline Kaalulangetus",
    svc1_desc: "Tõenduspõhine kaalulangetus vajadusel kaasaegsete ravimitega (GLP-1/GIP agonistid) kombineerituna toitumis- ja liikumisnõustamisega.",
    svc1_details: "Sisaldab konsultatsioone, vajadusel vereanalüüse, keha koostise monitooringut ja regulaarset järelevalvet.",
    svc1_price: "Programm alates 330€",
    svc2_title: "Pikaealisuse Protokoll",
    svc2_desc: "Südame-veresoonkonna riskide hindamine, bioloogilise vanuse analüüs ja ennetav tervisejuhtimine.",
    svc2_details: "Põhjalik tervisenäitajate analüüs, hormonaalne staatus ja unemeditsiin.",
    svc3_title: "Concierge-tasemel Tervisetugi",
    svc3_desc: "Personaalne ja kättesaadav tervisejuhtimine Sinu teekonnal parema tervise juurde.",
    svc3_details: "Otsesuhtlus kliinikuga, eelisjärjekorras vastuvõtud ja terviklik ravi koordineerimine.",
    phil_hero: "Meditsiiniline kaalulangetus ja pikaealisus Tallinnas.",
    phil_hero_sub: "Arstide juhitud kaalulangetus, muuhulgas GLP-1/GIP ravi ja metaboolne optimeerimine.",
    phil_usp1_title: "Isiklik kogemus",
    phil_usp1_desc: "Élan Kliiniku kontseptsiooni loomises on osalenud arstid, kes on ise kogenud elumuutvat kaalulangust. Me ei räägi ainult ravijuhistest — me teame omast käest hirme ja lootusi.",
    phil_usp2_title: "Erialane pädevus",
    phil_usp2_desc: "Meie meeskond koosneb spetsialistidest, kes ühendavad kliinilise kogemuse ja tänapäevased tõenduspõhised ravimeetodid.",
    phil_usp3_title: "Kliinilised eesmärgid",
    phil_usp3_desc: "Meie kliinilised protokollid on suunatud esmase 10–15% kehakaalu vähendamisele. Selle saavutamisel hindame uuesti üle eesmärgid, soovid ja võimalused ning jätkame kaalulanguse teise faasiga.",
    phil_usp4_title: "Stigmavaba lähenemine",
    phil_usp4_desc: "Me ei stigmatiseeri ega arvusta. Iga patsiendi teekond on isiklik ja me kohtleme teid austuse ning mõistmisega.",
    phil_founder_label: "Me teame, mis tunne see on",
    phil_founder_p1: "Élan Kliinik on sündinud arstide ja spetsialistide koostöös, kes on ise rasvumisega silmitsi seisnud.",
    phil_founder_p2: "Oleme ise läbi teinud nii esimesed süstid, esimesed kõrvaltoimed kui ka kogenud rõõmu sellest, kui kaal langema hakkab.",
    phil_founder_sig: "— Élan Kliiniku asutajad",
    phil_team_title: "Meie meeskond",
    phil_team_sub: "Teie heaks töötavad meie põhitiim — arstid ja õed. Vajadusel kaasame teiste valdkondade spetsialiste. Kõik spetsialistid teevad koostööd ühise eesmärgi nimel.",
    phil_member1_role: "Meditsiinijuht & Concierge arst",
    phil_member1_desc: "20+ aastat kogemust Eesti ja Soome meditsiinis. Kliiniku asutaja ja mentor. Spetsialiseerunud metaboolsele tervisele ja süsteemsele ennetustööle.",
    phil_member2_role: "Arst-resident (Peremeditsiin) & Kaasasutaja",
    phil_member2_desc: "Pühendunud tõenduspõhisele kaaluravile ja elustiilimeditsiinile.",
    phil_member3_role: "Õendusjuht & Kaasasutaja",
    phil_member3_desc: "Teie tugiisik raviteekonnal. Spetsialiseerunud klienditeenindusele, patsiendinõustamisele ja ravi järjepidevuse tagamisele.",
    phil_story_label: "Dr. Ingmar Lindström — Asutaja",
    phil_story_p1: "Olen olnud ülekaaluline üle 20 aasta — see kogemus on andnud mulle selge ja praktilise arusaama, et inimesed ei vaja ainult juhiseid, vaid kedagi, kes päriselt mõistab. See mõistmine on saatnud mind kogu mu teekonnal normaalse kehakaalu ja tervislike eluviiside poole. See tee ei olnud kiire ega sirgjooneline.",
    phil_story_p2: "Kaalu olen viimase 15 aasta jooksul langetanud mitmel eri moel:",
    phil_story_li1: "Üle 25 kg teadlikuma toitumise ja mindfulness'i abil",
    phil_story_li2: "Üle 10 kg vahelduva paastumisega",
    phil_story_li3: "Üle 30 kg kombinatsioonina põhjalikust elustiilimuutusest ja kaasaegsetest ravimitest nagu Semaglutiid ja Tirzepatiid",
    phil_story_p3: "Oluline erinevus viimases etapis oli see, et muutusest sai igapäevane eluviis, mitte ajutine projekt.",
    phil_story_p4: "Isiklik kogemus on andnud mulle midagi, mida meditsiin üksi ei paku: selge taju, mis päriselt toimib ning mis vajab inimese kõrval olemist, mitte pelgalt juhiste jagamist. Minu patsiendid on selle lähenemise abil kaotanud kokku üle 100 kilogrammi — kuid kõige olulisemad muutused peegelduvad enesekindluses, kergemas olemises ja igapäevase heaolu paranemises.",
    phil_story_quote: "Kanname kannatusi rohkem kujutluses kui tegelikkuses. — Seneca",
    phil_story_p5: "Meie kliiniku idee on lihtne: iga inimene väärib teenust, mis on sama isiklik kui tema teekond. Me kohandame lähenemise alati inimese järgi, mitte vastupidi.",
    phil_story_p6: "Élan ei ole suur ega lärmakas — see on teadlik valik. Eelistame vaikset, professionaalset tähelepanelikkust ja pühendunud meeskonda, kelle fookus on sellel, mida kaalulangus inimesele tegelikult võimaldab: kergem elu, parem tervis ja pikem tervena elatud aeg.",
    phil_story_p7: "Kui oled alustamas või uuesti alustamas, oled jõudnud õigesse kohta.",
    book_headline: "Kujundame koos Teie tervise teekonna.",
    book_subtext: "Palun valige teenus, millega soovite alustada.",
    book_loading: "Laadimine...",
    book_cancel_title: "Tühistamise reeglid",
    book_cancel_text: "Palume teatada mitteosalemisest vähemalt 24h ette.",
    book_contact: "Võta ühendust",
    book_card1_title: "Meditsiiniline Kaalulangetus",
    book_card1_sub: "12-kuuline programm ja GLP-1/GIP nõustamine.",
    book_card2_title: "Pikaealisuse Konsultatsioon",
    book_card2_sub: "Biomarkerite analüüs ja ennetav terviseprotokoll.",
    book_card3_title: "Esmane Terviseaudit",
    book_card3_sub: "30-minutiline kaardistamine.",
    book_seo_summary: "Élan Kliinik pakub meditsiinilist kaalulangust, pikaealisuse konsultatsioone ja esmast terviseauditit Tallinnas. Broneerige aeg veebis või võtke ühendust telefonil +372 5803 0033.",
    book_acuity_headline: "Broneeri oma terviseaudit",
    book_acuity_loading: "Laen broneerimissüsteemi...",
    book_concierge_loading: "Valmistame ette Teie personaalset broneerimiskeskkonda...",
    ty_headline: "Täname usalduse eest.",
    ty_body: "Teie broneering on kinnitatud. Élan Kliiniku meeskond on Teie teekonnaks ettevalmistusi alustamas.",
    ty_step1_title: "Kinnitus",
    ty_step1_desc: "Saate koheselt kinnituse e-posti teel.",
    ty_step2_title: "Küsimustik",
    ty_step2_desc: "Saadame Teile 24h jooksul lühikese terviseloole keskenduva küsimustiku.",
    ty_step3_title: "Vastuvõtt",
    ty_step3_desc: "Kohtume valitud ajal meie kliinikus.",
    ty_cta: "Tagasi pealehele",
    lead_headline: "Kuidas saavutada püsiv muutus?",
    lead_subtext: "Lae alla meie metaboolse edu protokoll ja liitu meie eelisjärjekorra nimekirjaga.",
    lead_subtext2: "",
    lead_name: "Eesnimi",
    lead_email: "E-posti aadress",
    lead_cta: "Saada juhend",
    lead_success: "Täname! Kontrollige oma e-posti. Juhend ja sooduskood on teel.",
  },
  en: {
    nav_home: "Home",
    nav_about: "About",
    nav_services: "Services",
    nav_faq: "FAQ",
    nav_cta: "Contact",
    hero_headline: "Restore balance. Improve health. Feel better.",
    hero_subtitle: "Élan Clinic is Estonia's evidence-based longevity and medical weight loss clinic.",
    hero_cta: "Book Consultation",
    why_title: "Why choose Élan Clinic?",
    val_personal_title: "Personal experience",
    val_personal_desc: "We know how it feels — we've walked this path ourselves.",
    val_evidence_title: "Evidence-based",
    val_evidence_desc: "Medications and protocols based on European clinical guidelines.",
    val_longterm_title: "Long-term support",
    val_longterm_desc: "Up to 24-month comprehensive programme.",
    about_title: "Philosophy",
    about_desc: "Élan Clinic combines top-tier medicine with personalised care. Our goal isn't just a number on the scale — it's your quality of life.",
    about_cta: "Read our story",
    footer_nav: "Navigation",
    footer_contact: "Contact",
    footer_address: "Address",
    footer_phone: "Phone",
    footer_email: "Email",
    footer_hours: "Open",
    footer_hours_value: "Mon–Fri 09:00 – 17:00",
    footer_rights: "All rights reserved.",
    footer_privacy: "Privacy Policy",
    svc_title: "Services",
    po_title: "Élan Private Office",
    po_subtitle: "Personal health partnership. Limited availability.",
    po_desc: "Designed for those who do not compromise on health. Complete medical logistics and proactive health management for the individual who values time, privacy, and direct access to their physician.",
    po_price: "From €1,000 / month",
    po_cta: "Apply for membership",
    po_who: "Who is this for?",
    po_page_desc: "Exclusive health management under the personal supervision of Dr. Ingmar Lindström.",
    nav_private: "Private Office",
    svc_subtitle: "Evidence-based treatment programmes tailored to your needs.",
    svc_book: "Book",
    svc1_title: "Medical Weight Loss",
    svc1_desc: "Evidence-based weight loss with modern medications (GLP-1/GIP agonists) combined with nutrition and exercise counselling when needed.",
    svc1_details: "Includes consultations, blood tests when needed, body composition monitoring and regular follow-up.",
    svc1_price: "Programme from €330",
    svc2_title: "Longevity Protocol",
    svc2_desc: "Cardiovascular risk assessment, biological age analysis and preventive health management.",
    svc2_details: "Comprehensive health marker analysis, hormonal status and sleep medicine.",
    svc3_title: "Concierge Health Support",
    svc3_desc: "Personal and accessible health management on your journey to better health.",
    svc3_details: "Direct communication with the clinic, priority appointments and comprehensive care coordination.",
    phil_hero: "Medical weight loss and longevity in Tallinn.",
    phil_hero_sub: "Physician-led weight loss, including GLP-1/GIP therapy and metabolic optimisation.",
    phil_usp1_title: "Personal experience",
    phil_usp1_desc: "Élan Clinic was created by physicians who have personally experienced life-changing weight loss. We don't just cite guidelines — we know the fears and hopes firsthand.",
    phil_usp2_title: "Professional expertise",
    phil_usp2_desc: "Our team combines clinical experience with modern evidence-based treatment methods.",
    phil_usp3_title: "Clinical targets",
    phil_usp3_desc: "Our clinical protocols target an initial 10–15% body weight reduction. Once achieved, we reassess goals, preferences and options and continue with the second phase.",
    phil_usp4_title: "Stigma-free approach",
    phil_usp4_desc: "We do not stigmatise or judge. Every patient's journey is personal and we treat you with respect and understanding.",
    phil_founder_label: "We know how it feels",
    phil_founder_p1: "Élan Clinic was born from a collaboration of physicians and specialists who have personally faced obesity.",
    phil_founder_p2: "We have been through the first injections, the first side effects, and the joy of seeing the weight start to come off.",
    phil_founder_sig: "— Founders of Élan Clinic",
    phil_team_title: "Our team",
    phil_team_sub: "Your care is delivered by our core team — physicians and nurses. When needed, we involve specialists from other fields. All professionals work together towards one common goal.",
    phil_member1_role: "Medical Director & Concierge Physician",
    phil_member1_desc: "20+ years of experience in Estonian and Finnish medicine. Clinic founder and mentor. Specialised in metabolic health and systemic prevention.",
    phil_member2_role: "Resident Physician (Family Medicine) & Co-founder",
    phil_member2_desc: "Dedicated to evidence-based weight management and lifestyle medicine.",
    phil_member3_role: "Head Nurse & Co-founder",
    phil_member3_desc: "Your support person throughout the treatment journey. Specialised in patient counselling and ensuring continuity of care.",
    phil_story_label: "Dr. Ingmar Lindström — Founder",
    phil_story_p1: "I have been overweight for over 20 years — this experience has given me a clear and practical understanding that people need not just guidelines, but someone who truly understands. This understanding has accompanied me throughout my journey towards a healthy weight and lifestyle. The path was neither quick nor straightforward.",
    phil_story_p2: "Over the past 15 years, I have lost weight in several different ways:",
    phil_story_li1: "Over 25 kg through mindful eating and mindfulness",
    phil_story_li2: "Over 10 kg through intermittent fasting",
    phil_story_li3: "Over 30 kg through a combination of comprehensive lifestyle change and modern medications such as Semaglutide and Tirzepatide",
    phil_story_p3: "The key difference in the last phase was that the change became a daily way of life, not a temporary project.",
    phil_story_p4: "Personal experience has given me something that medicine alone cannot offer: a clear sense of what truly works and what requires being beside a person, not merely dispensing instructions. My patients have collectively lost over 100 kilograms through this approach — but the most important changes are reflected in confidence, lighter being and improved daily well-being.",
    phil_story_quote: "We suffer more in imagination than in reality. — Seneca",
    phil_story_p5: "Our clinic's idea is simple: every person deserves a service as personal as their journey. We always adapt the approach to the person, not the other way around.",
    phil_story_p6: "Élan is not big or loud — that is a deliberate choice. We prefer quiet, professional attentiveness and a dedicated team whose focus is on what weight loss truly enables: a lighter life, better health and more years lived in good health.",
    phil_story_p7: "If you are starting or starting again, you have come to the right place.",
    book_headline: "Let's redesign your health journey.",
    book_subtext: "Please choose the service you'd like to begin with.",
    book_loading: "Loading...",
    book_cancel_title: "Cancellation policy",
    book_cancel_text: "Please notify us at least 24 hours in advance if you cannot attend.",
    book_contact: "Get in touch",
    book_card1_title: "Medical Weight Loss",
    book_card1_sub: "12-month programme and GLP-1/GIP counselling.",
    book_card2_title: "Longevity Consultation",
    book_card2_sub: "Biomarker analysis and preventive health protocol.",
    book_card3_title: "Initial Health Audit",
    book_card3_sub: "30-minute health mapping.",
    book_seo_summary: "Élan Clinic offers medical weight loss, longevity consultations and initial health audits in Tallinn. Book an appointment online or contact us at +372 5803 0033.",
    book_acuity_headline: "Book your health audit",
    book_acuity_loading: "Loading booking system...",
    book_concierge_loading: "Preparing your personal booking environment...",
    ty_headline: "Thank you for your trust.",
    ty_body: "Your booking is confirmed. The Élan Clinic team is beginning preparations for your journey.",
    ty_step1_title: "Confirmation",
    ty_step1_desc: "You will receive an immediate confirmation via email.",
    ty_step2_title: "Questionnaire",
    ty_step2_desc: "We will send you a brief health history questionnaire within 24 hours.",
    ty_step3_title: "Appointment",
    ty_step3_desc: "We will meet at your chosen time at our clinic.",
    ty_cta: "Back to home",
    lead_headline: "How to achieve lasting change?",
    lead_subtext: "Download our Metabolic Success Protocol and join our priority list.",
    lead_subtext2: "",
    lead_name: "First name",
    lead_email: "Email address",
    lead_cta: "Send the guide",
    lead_success: "Thank you! Check your email. The guide and discount code are on their way.",
  },
} as const;

type Translations = Record<keyof typeof translations.et, string>;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("et");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
